exports.PROJECT_PATH = '/Users/luanamartins/Documents/Mestrado/project-analysis/extract-metrics/'
exports.DATA_PROJECT_PATH = '/Users/luanamartins/Documents/Mestrado/project-analysis/extract-metrics/data/'
exports.SRC_PATH = '/Users/luanamartins/Documents/Mestrado/project-analysis/extract-metrics/src/'
exports.TEST_PATH = '/Users/luanamartins/Documents/Mestrado/project-analysis/extract-metrics/test/'
exports.DATA_TEST_PATH = '/Users/luanamartins/Documents/Mestrado/project-analysis/extract-metrics/test/data/'
exports.SAVE_METRIC_FILES_PATH = '/Users/luanamartins/Documents/Mestrado/project-analysis/results/results-2018-06-29/metrics-files/'